/* GENERATED by tools/gen-params.py --netid jmontroy -- do not edit by hand.
 * Re-run it if your netid changes; nothing else in this repository affects
 * your seed.
 *
 * This header carries only NUMBERS. It does not say which pathology is
 * active -- src/workload.c derives that itself from WL_SEED, and finding out
 * which one you have is the assignment (see the handout). */
#ifndef WL_PARAMS_H
#define WL_PARAMS_H

/* Up to 48 bits -- always take this as uint64_t, never `unsigned` (32-bit
 * platforms silently truncate it, and a truncated seed no longer matches the
 * one your netid derives). */
#define WL_SEED       250717358276124ull
#define WL_WORKERS    4u
#define WL_SIZE_0     1000u
#define WL_SIZE_1     2000u
#define WL_SIZE_2     20000u
#define WL_SIZE_3     100000u
#define WL_REPEATS    3u

#endif /* WL_PARAMS_H */
