#!/usr/bin/env python3
"""
gen-params.py - derive YOUR seeded workload from your netid.

`derive()` and `gen_sweep()` below are VENDORED, byte-for-byte, from the
course's own copy -- do not "fix" or restyle the arithmetic in them. The
configuration is re-derived from your netid when your work is read, using
those same two functions; if this file's arithmetic ever disagreed with the
original, every number you reported would describe a different program, and
nothing would say so.

This header carries only NUMBERS -- your seed, worker count, task sizes and
warm-up count. It does NOT say which of the three pathologies is active.
`src/workload.c` derives that itself from WL_SEED, at runtime -- read it if
you want to (nothing here is encrypted), but see its file header for why
that reading does not substitute for the measurement this assignment asks
for.

Usage:
    python3 tools/gen-params.py --netid jsmith42

Writes config/params.h, which src/workload.c compiles against. Re-run it if
your netid changes; nothing else in this repository affects your seed.
"""
from __future__ import annotations

import argparse
import hashlib
import random
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "config" / "params.h"
LABEL = "A5"
SEED_HEX_DIGITS = 12  # part of the derivation -- do not change


def derive(netid: str, label: str) -> int:
    """Part of the course's own derivation, written out here. Do not edit."""
    key = f"{netid.strip().lower()}:{label.strip().upper()}".encode("utf-8")
    digest = hashlib.sha256(key).hexdigest()
    return int(digest[:SEED_HEX_DIGITS], 16)


def gen_sweep(seed: int) -> dict:
    """Part of the course's own derivation, written out here. Do not edit."""
    rng = random.Random(seed)
    size_pool = [1_000, 2_000, 5_000, 10_000, 20_000, 50_000, 100_000]
    worker_pool = [1, 2, 3, 4, 6, 8, 12]
    return {
        "sizes": sorted(rng.sample(size_pool, k=4)),
        "workers": sorted(rng.sample(worker_pool, k=3)),
        "repeats": rng.randint(3, 5),
    }


#: A5's OWN use of the derived seed -- not part of the vendored functions
#: above. The median of the three sampled worker counts, floored at 3 so
#: uneven-partition always has at least one worker on each of its two shards.
MIN_WORKERS = 3

HEADER_TEMPLATE = """\
/* GENERATED by tools/gen-params.py --netid {netid} -- do not edit by hand.
 * Re-run it if your netid changes; nothing else in this repository affects
 * your seed.
 *
 * This header carries only NUMBERS. It does not say which pathology is
 * active -- src/workload.c derives that itself from WL_SEED, and finding out
 * which one you have is the assignment (see the handout). */
#ifndef WL_PARAMS_H
#define WL_PARAMS_H

/* Up to 48 bits -- always take this as uint64_t, never `unsigned` (32-bit
 * platforms silently truncate it, and a truncated seed no longer matches the
 * one your netid derives). */
#define WL_SEED       {seed}ull
#define WL_WORKERS    {workers}u
#define WL_SIZE_0     {size0}u
#define WL_SIZE_1     {size1}u
#define WL_SIZE_2     {size2}u
#define WL_SIZE_3     {size3}u
#define WL_REPEATS    {repeats}u

#endif /* WL_PARAMS_H */
"""


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--netid", required=True, help="your netid, exactly as the roster has it")
    args = ap.parse_args()

    seed = derive(args.netid, LABEL)
    sweep = gen_sweep(seed)
    workers = max(sweep["workers"][1], MIN_WORKERS)   # median of the 3, floored

    header = HEADER_TEMPLATE.format(
        netid=args.netid, seed=seed, workers=workers,
        size0=sweep["sizes"][0], size1=sweep["sizes"][1],
        size2=sweep["sizes"][2], size3=sweep["sizes"][3],
        repeats=sweep["repeats"])

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header)
    print(f"wrote {OUT} for netid {args.netid!r}")
    print(f"  seed={seed} workers={workers} sizes={sweep['sizes']} repeats={sweep['repeats']}")
    print("  config/params.h has your numbers. It does not say which of the three")
    print("  pathologies is active -- run `make bench` and measure.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
